export const projectData = [
    {
        id: 0,
        title: "Andrew's Silly React Quiz",
        description:"This application is built on ReactJS and is intended to test your knowledge on it as well! Once you open the app, you will be presented with a button. Upon pressing the button, you will have activated the quiz. Each question allows ten seconds to answer so think fast and have fun!",
        build: ["ReactJS","CSS","Node.js","Express","Webpack","Babel"],
        link: "https://andrewsreactquiz.herokuapp.com/",
        projectType: "REACT",
        imgRef: "RQ",
        pngRef: "reactQuiz.png",
    },{
        id: 1,
        title: "Search Cuisine & Wine!",
        description:"This application is built on ReactJS and spoonacular's API. You can use this application to search for new Cuisine recipies or Wine recommendations. For the Cuisine search you may include an intolerances perameter which will exclude certain meals from your search based on dietary restrictions.",
        build: ["ReactJS","CSS","Node.js","Express","Webpack","Babel","Spoonacular API"],
        link: "https://search-cuisine-siricoa94.herokuapp.com/home",
        projectType: "REACT",
        imgRef: "SCW",
        pngRef: "scw.png",
    },{
        id: 2,
        title: "Dragonball Hangman",
        description:"Above is a game I created called Dragonball hangman! This is one of my earlier projects, and although quite simple, it encapsulates the classic hangman experience. Even the most seasoned Dragonball fan will find difficulty in guessing the correct name, but no worries as you can always keep playing just by pressing another key!",
        build: ["HTML","CSS","JavaScript"],
        link: "https://siricoa94.github.io/WordGuessTwo/",
        projectType: "LEGACY",
        imgRef: "DBHM",
        pngRef: "dragonball.png",
    },{
        id: 3,
        title: "Hominid Trivia Game",
        description:"Hominid Trivia Game is a mobile friendly application that tests your knowledge on the origins of the human species. Although simple in scope, this application is easy on the eyes as well as entertaining.",
        build: ["HTML","CSS","JavaScript"],
        link: "https://siricoa94.github.io/HominidTriviaGame/",
        projectType: "LEGACY",
        imgRef: "HTG",
        pngRef: "hominid.png",
    },{
        id: 4,
        title: "Burgers!",
        description:"This is an app designed for the user to create a burger. They can enter a name, and also set the state of the burger to either Fresh or Devoured! After the burger is made, the user can devour the burger, or make it fresh, and watch it switch sides.",
        build: ["HTML","CSS","JavaScript","Node.js","Express","Express-handlebars","MySQL","Sequelize"],
        link: "https://ancient-springs-99908.herokuapp.com/",
        projectType: "LEGACY",
        imgRef: "BGS",
        pngRef: "burgers.png",
    },{
        id: 5,
        title: "Found Sound",
        description:"Found Sound is the perfrect application for anyone who would like to sample some music by an artist. Simply type into the search bar an artist, song, or album name and Found Sound will return you a list of samples based off the search phrase that was provided. Having a simple, yet elegant design, sound found is easy to navigate and use for any user.",
        build: ["HTML","CSS","JavaScript","jQuery","Node.js","Express"],
        link: "https://foundsound.herokuapp.com/",
        projectType: "LEGACY",
        imgRef: "FS",
        pngRef: "foundSound.png",
    },{
        id: 6,
        title: "Rico Depot",
        description:"Rico Depot is a marketplace/game application that works as follows. Upon signing up a user is given 10,000 credits and is allowed to purchase products listed on the products page. When a user buys a product, their purchase history will be appened to their homepage. Users can also view how their spending habits score up against other users on the leaderboard page.",
        build: ["HTML","CSS","JavaScript","jQuery","Node.js","Express","MySQL","Firebase"],
        link: "https://ricodepot.herokuapp.com/",
        projectType: "LEGACY",
        imgRef: "RD",
        pngRef: "ricoDepot.png",
    }
]